### ISSUE TITLE
Wrong ordering of tiling factors

### ISSUE THREAD

**Issue by colluca** [cmlasu/dMazeRunner#2]
Hi,

I'm reviewing the code to adapt it to an algorithm of my own.
I believe there is a mistake in https://github.com/MPSLab-ASU/dMazeRunner/blob/master/python/dMazeRunner/common/optimizer.py on line 66. 
Shouldn't ox and oy be inverted? I guess this mistake could have gone unnoticed due to testing with equal output width and height tiling factors.

Correct me if I'm mistaken.
Best, Luca

**Comment by shail-dave** [comment]
Hi Luca,

Thank you very much for your interest and for pointing this out. Yes, the ordering of some loop index variables should be inverted. I have updated the code with a consistent ordering of loop index variables for packing and unpacking the tuples of index variables.

Best regards,
Shail
